### PR TITLE
111 - Update Helper Functions To Use Default Exports

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number

#111

The initial commit of this PR starts at [4621776](https://github.com/AlexsLemonade/refinebio-web/pull/113/commits/46217767fdc90c0dc6fec63c7a1d006eac2767f8) and ends at [af28acf](https://github.com/AlexsLemonade/refinebio-web/pull/113/commits/af28acf6df6c828ce889eadd2ef7b60c1631d15e) (total 7 commits).

Updated helper functions to use the default export with arrow functions and modified helper import statements in the codebase to reflect these changes.

No UI review required for this PR,  thank you!

## Types of changes
 New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by nozomione** [comment]
@davidsmejia as requested today's 1:1, I prepared the PRs for you to review tomorrow during the time you allocated time for PR review.

**2** of 3

This is trivial and iterative but safe PR to merge into `dev`, since it's the export update for helpers. Also this is one of the common causes for merge conflicts in the new PRs, so it's good to take care of it. Let me know if you have any questions!

**Comment by davidsmejia** [comment]
Looking good, please update to flatten the helpers. They should be named generically and if they are tied to the context they probably belong in the hook. You can rename the helpers/search helpers to describe what they are doing more generically.

**Comment by nozomione** [comment]
> Looking good, please update to flatten the helpers. They should be named generically and if they are tied to the context they probably belong in the hook. You can rename the helpers/search helpers to describe what they are doing more generically.

Those helpers for /dataset and /search will be removed, flattened, or moved to managers in the later PRs 👍

**Comment by nozomione** [comment]
Closing this PR w/o merge since it's simply to format the helper files (this change is already included in `dev`), thank you.

**Pull request closed without merging**
