### PR TITLE
36 - Implement Samples Table

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number
#36 

**Dependencies:** [35 - Implement Compendia Page](https://github.com/AlexsLemonade/refinebio-web/pull/39), [37 - Add Responsive to Search Result Page](https://github.com/AlexsLemonade/refinebio-web/pull/38)
**Figma Mockup:** [Experiment](https://www.figma.com/file/2cxEjUKA4ACTjDYSnDEWpR/refinebio-master?node-id=37%3A1765&t=elFXqC6cONF3EFD8-0)

**NOTE:** This feature branch;
-  was created based on the `nozomione/35-implement-compendia-page` branch
-  includes(pulled) the latest update of the `nozomione/37-add-responsive-to-search-result-page` branch

This is a dependent of [(PR) 35 - Implement Compendia Page ](https://github.com/AlexsLemonade/refinebio-web/pull/39) and [(PR) 37 - Add Responsive to Search Result Page](https://github.com/AlexsLemonade/refinebio-web/pull/38) and the actual commit starts at [b6dfe26](https://github.com/AlexsLemonade/refinebio-web/pull/41/commits/b6dfe26e8492a310d9ad4be972aeeb31e2995d38).

Implemented the Samples Table

<details>
<summary>Files related to this PR</summary><br />

</details>

- [x] UI review w/ @dvenprasad - please review the UI [latest](https://refinebio-no8ay1fkx-ccdl.vercel.app), thank you!
 (After passing the UI review, @davidsmejia will be added to the reviewers.)

1) Please review the top two cards on the search results page for the expandable table feature.
image

2) Please note that the maximum width of the "Add/Remove" and "Accession Code" columns is currently set to 160px, however they can collapse to 60px just like other columns  when resizing.
image

## Types of changes

- New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by nozomione** [comment]
@dvenprasad , I updated the following items and now the UI([lastest](https://refinebio-no8ay1fkx-ccdl.vercel.app)) is ready for your review, thank you!

- Update the Filter's placeholder text to be 'Filter samples'
- Update the row hover color to be 'brand-tint-80'(#d4e1f1) and fix a bug where odd rows are not highlighted on hover
- Show a horizontal scroll bar in the data table but hide a vertical scroll bar
- Make the text in each cell wrap and show the ellipsis after the cell has shrunk to 100px in width

**Comment by dvenprasad** [comment]
@nozomione All the changes look good! 

I have one comment for the horizontal scroll bar: It disappears after a bit. Is it possible to make it persistent? This horizontal scrollbar is an issue for windows users who do not not sufficient support for scrolling horizontally.

**Comment by dvenprasad** [comment]
Yeah, it's an issue with being able to scroll sideways. It's easier to do that on mac, or trackpads, but much harder on a windows machine. 

I'm going to approve this for now, I'll keep an eye out for this during evals.

**Review by dvenprasad — APPROVED** [review]
🦞 🦞 🦞

**Comment by nozomione** [comment]
Suggestions for `InlineMessage` component: https://github.com/AlexsLemonade/refinebio-web/pull/32#discussion_r1119174613

**Comment by nozomione** [comment]
🗒️ As mentioned in 1:1, due to the changes made in the recent PRs (API integration for search, experiments, and samples (in progress) endpoints),  I’ll be closing any PRs that are no longer relevant . Since the shared components used for the samples table were updated (this includes cleanup of logic added for the mock data), I am closing this PR as well. 

Once this process will completed, I will let you know, thank you @davidsmejia !

**Pull request closed without merging**
