### PR TITLE
109 - Clean Up Custom Variables And Use Grommet Responsive Prop For Heading Component

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number

#109

- This is the updated theme variables that are used in our codebase (relevant closed PR [110](https://github.com/AlexsLemonade/refinebio-web/pull/110)([note](https://github.com/AlexsLemonade/refinebio-web/pull/110#issuecomment-1614036890))). 
- The initial commit of this PR starts at [be36dd6](https://github.com/AlexsLemonade/refinebio-web/pull/112/commits/be36dd6ac45b8b8399b4dbfd7808a97020dd30d7) and ends at [d1115a6](https://github.com/AlexsLemonade/refinebio-web/pull/112/commits/d1115a66a2f8b28fb009c3d773ac05ce72ccd16c) (total 3 commits).

Cleaned up the custom variables and utilized the Grommet's `responsive` prop and `useResponsive` hook in JSX when necessary, otherwise updated the value of the `size` prop.

**NOTE:** I merged the `dev`.

## Types of changes
 New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by nozomione** [comment]
@davidsmejia as requested today's 1:1, I prepared the PRs for you to review tomorrow during the time you allocated time for PR review.

**1** of 3

This is trivial and iterative but safe PR to merge into `dev`, since it's the theme update for the site's layout. Also this is one of the common causes for merge conflicts in the new PRs, so it's good to take care of it first. Let me know if you have any questions!

**Review by davidsmejia — APPROVED** [review]
LGTM - one thing to consider here would be inverting the responsive flag so that you can just pass `noresponsive` if you don't want the `Header` to resize.

**Comment by nozomione** [comment]
> LGTM - one thing to consider here would be inverting the responsive flag so that you can just pass `noresponsive` if you don't want the `Header` to resize.

🗒️  For the responsive, we're utilizing the Grommet's built-in [`responsive`](https://v2.grommet.io/heading#responsive) prop for non-scale headings.

**Comment by nozomione** [comment]
Closing this PR w/o merge since it's simply to clean up the custom variables (this change is already included in `dev`), thank you.

**Pull request closed without merging**
