### PR TITLE
35 - Implement Compendia Page

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number
#35 

**Dependency:** [#33](https://github.com/AlexsLemonade/refinebio-web/pull/33) 
**Figma Mockup:** [Compendia](https://www.figma.com/file/2cxEjUKA4ACTjDYSnDEWpR/refinebio-master?node-id=127%3A5570&t=t2FM8JKBT1UdDje5-0)

(This PR is a dependent of PR [#33](https://github.com/AlexsLemonade/refinebio-web/pull/33) and was created based on the branch [`nozomione/30-implement-about-page`](https://github.com/AlexsLemonade/refinebio-web/tree/nozomione/30-implement-about-page). The actual commits for this PR starts at: [627885f](https://github.com/AlexsLemonade/refinebio-web/pull/39/commits/627885f1ee0ff35c4857da0061dcb3ac0ee4b918).)

Implemented the Compendia page including responsive using the mock data.

<details>
<summary>Files related to this PR</summary><br />

</details>

- [x] UI review w/ @dvenprasad - please review the UI [here](https://refinebio-md7epfflo-ccdl.vercel.app), thank you!

(After passing the UI review, @davidsmejia will be added to the reviewers.)
## Types of changes

- New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by nozomione** [comment]
@dvenprasad I updated the following items and the UI is ready for your review, thank you!
- Increased the border width(active to 3px/hover to 2px) for the tabs
- Updated the 'quant.sf' text's background color to be #f2f2f2 against the white background
- Updated the search box for the compendia download with filtering based on a user input

**Review by dvenprasad — CHANGES_REQUESTED** [review]
All of it looks good!

There seems to be some sort of a lag for the search box. If I type at my regular speed, some characters get swallowed up. But if I slow down, it manages capture all of the keystrokes.

**Comment by nozomione** [comment]
> There seems to be some sort of a lag for the search box. If I type at my regular speed, some characters get swallowed up. But if I slow down, it manages capture all of the keystrokes. 

@dvenprasad  I updated the search box and now it works without the delay. Please review at [here](https://refinebio-l0g29nw7v-ccdl.vercel.app) thank you!

**Review by dvenprasad — APPROVED** [review]
Working smoothly! 
🦆 🦆 🦆

**Review by davidsmejia — APPROVED** [review]
LGTM

**Pull request merged**
